### ISSUE TITLE
Construct Multisig-based security council

### ISSUE THREAD

**Issue by chokobole** [kroma-network/kroma#18]
### Issue Type

Feature Request

### Kroma Version

0.1.1

### OS Platform and Distribution

Linux Ubuntu 22.04

### Go version

go1.19.3 linux/amd64

### Node version

v16.14.2

### Changes

As [vitalik prpoposed](https://ethereum-magicians.org/t/proposed-milestones-for-rollups-taking-off-training-wheels/11571),  
when ZK Fault proof soundness is exploited, the challenge process must be corrected by security council. This is going to be fully implemented until June and audited before mainnet launch.

See belows for reference.

As you can see in the reference figure, Our Multisig-based scenario is related to the challenge. Specifically, it is as follows.

proof presented by Challenger passes protocol
(1) Challenge success - Make sure the validity of the proof
(2) Challenge fail - Zero knowledge proof soundness error

### Tasks

- [x] Implement multisig-based contract that performs the behavior of accepting / approving / executing transactions for the promised whitelists. (https://github.com/kroma-network/kroma/pull/57)
- [x] Develop multisig node. This node communicates with the multisig contract, validating the output root and passing signature for the result.
- [x] Integration with Challenge process(with Colosseum)

**Comment by 0xHansLee** [comment]
I think this issue has been resolved. Please check and close @kangsorang @Pangssu

**Comment by kangsorang** [comment]
All tasks have been completed. The issue is resolved.
