### ISSUE TITLE
Allow multiple validators to submit output

### ISSUE THREAD

**Issue by chokobole** [kroma-network/kroma#19]
### Issue Type

Feature Request

### Kroma Version

0.1.0

### OS Platform and Distribution

Linux Ubuntu 22.04

### Go version

go1.19.3 linux/amd64

### Node version

v16.14.2

### Changes

Currently a single validator only submits output, which is called _validation_. For the next release, we want to contain permissionless validation. 

**TL;DR** 

1. `Fee vaults` would be divided into three categories based on its purpose. `Proposer Reward Vault`, `Protocol Vault` and `Validator Reward Vault`.
2. Validators need to submit output with a _bond_ of at least minimum bond amount.
3. Validators receive a reward in exchange for submitting an output.
4. Validators needs to initiate a challenge with a _bond_.
5. The amount of minimum bond and reward can dynamically vary depending on the protocol.

Optimism distinguishes between three different types of funding sources: `ProposerFeeVault`, `BaseFeeVault`, and `RollupFeeVault`, based on their origin. In the upcoming release of Kroma, funds will be divided into `ProposerRewardVault`, `ProtocolVault`, and `ValidatorRewardVault`, based on their purpose. The `ProposerRewardVault` will be similar to the existing `RollupFeeVault`. Of the total fee (sum of base fee and priority fee), a proportion _R_ (`Validator Reward Ratio`) will go to the `ValidatorRewardVault`, while the remaining amount will go to the `ProtocolVault`. The funds in the `ValidatorRewardVault` will be used solely for rewarding validators, while the `ProtocolVault` will be used for the development of the protocol.

_R_ is designed considering the following:

- _R_ is not fixed but dynamically set depending on the situation.
- _R_ is updated in the L1Block contract via DepositTx when every L2 block is created.
- However, we haven't found any factors that would change the current _R_, so we'll need to do some research and temporarily fix it at a certain value. (probably 0.2)

To participate in the validation process, a validator must stake a certain amount of bond, but if the bonding amount is too high, the profitability will decrease, and if it is too low, it may lead to abuse. Therefore, to ensure that the staking profitability is similar to that of ETH staking, it is important to set $R_{min}$ and $R_{max}$ appropriately. If the output submitted by a validator is successfully finalized, they can claim a share of the amount present in the `ValidatorRewardVault` at that time proportional to their contribution. However, there is a submission timeout for validation, and if the output is not submitted within that timeout, the trusted validator will receive the reward.

In addition, the validation bonding amount should be proportional to the `ValidatorRewardVault` and inversely proportional to the number of pending output submissions.

```math
\displaylines{
B_{required} = \alpha \times \frac {V_{vault}}{B_{base} \times O_{waiting}}, \text{where } 0 \le \alpha \lt 1 \\
\\
B_{required} = \text{The required bonding amount} \\
V_{vault} = \text{The balance of validator reward vault} \\
B_{base} = \text{The base bonding amount, 1 / (10 *24 * 7) ETH} \\
O_{waiting} = \text{The number of waiting output submission} \\
}
```

On the other hand, the challenge bonding amount is initially similar to the validation bonding amount, but as the finalized period approaches, the required amount increases. This is to prevent attacks that try to prevent the output from being finalized by challenging it at the last minute. Currently, the finalization period of our chain is 7 days after the output submission, and there is only one challenge, so there are no immediate problems such as [delay attacks], but it is still an issue that needs to be discussed. In a similar context, the challenge reward ratio also decreases as the finalization period approaches.

[delay attacks]: https://offchain.medium.com/solutions-to-delay-attacks-on-rollups-434f9d05a07a

#### TODO

As a first implementation, the protocol will reward only the one who submits the output the fastest. Such a design will make only a few validators with high-spec devices participate in the network. To prevent this, we need to use VRF (verifiable random function) or Round-robin to ensure that everyone has a fair chance.

### Tasks

- [x] Activate `ValidatorPool.sol` and `Colosseum.sol`. allow only registered validators to submit output with a bond. (https://github.com/kroma-network/kroma/pull/53)
- [x] Require a challenger to stake a bond to initiate challenge. (https://github.com/kroma-network/kroma/pull/53)
- [x] Unbond if the associated output has passed finalization period. (https://github.com/kroma-network/kroma/pull/53)
- [x] The Security Council must approve the challenge result when the challenger wins. (https://github.com/kroma-network/kroma/pull/64)
- [x] Give the validator a _validation reward_ if the associated output has passed finalization period, and the validator or someone else submits the output. (https://github.com/kroma-network/kroma/pull/61)
- [ ] Update _validator reward ratio_ at every output submission.
- [x] Rename `ProposerFeeVault.sol`, `BaseFeeVault.sol` and `RollupFeeVault.sol`. (https://github.com/kroma-network/kroma/pull/47)
- [x] Distribute (base fee + priority fee) into `ProtocolVault.sol` and `ValidationRewardVault.sol`. (https://github.com/kroma-network/go-ethereum/pull/36)
- [x] Set `coinbase`/`suggestFeeRecipient` to zero address.

**Comment by TomTaehoonKim** [comment]
> Optimism distinguishes between three different types of funding sources: ProposerFeeVault, BaseFeeVault, and RollupFeeVault, based on their origin. In the upcoming release, funds will be divided into ProposerRewardVault, ProtocolVault, and ValidatorRewardVault, based on their purpose.

@chokobole In the phrase "In the upcoming release", whose release is it referring to?

**Comment by chokobole** [comment]
@TomTaehoonKim 

- It's `Kroma's` release.
- Oh, yeah I fixed it. The issue template was fixed but the existing issue remains untouched..
- Good point, I'll fix it.
